import pyrosim.pyrosim as pyrosim

def Generate_Body():
    pyrosim.Start_URDF("body4.urdf")
    pyrosim.Send_RD(name="zero0", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.Send_Joint(name = "zero0_zero1" , parent= "zero0" , child = "zero1" , type = "fixed", position = [0, 4.086, 0])
    pyrosim.Send_RD(name="zero1", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.Send_Joint(name = "zero1_zero2" , parent= "zero1" , child = "zero2" , type = "fixed", position = [0, 4.086, 0])
    pyrosim.Send_RD(name="zero2", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.Send_Joint(name = "zero2_zero3" , parent= "zero2" , child = "zero3" , type = "fixed", position = [0, 4.086, 0])
    pyrosim.Send_RD(name="zero3", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.Send_Joint(name = "zero3_half3half" , parent= "zero3" , child = "half3half" , type = "fixed", position = [2.88, -2.043, 2.043])
    pyrosim.Send_RD(name="half3half", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.Send_Joint(name = "half3half_half2half" , parent= "half3half" , child = "half2half" , type = "fixed", position = [0, -4.086, 0])
    pyrosim.Send_RD(name="half2half", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.Send_Joint(name = "half2half_half1half" , parent= "half2half" , child = "half1half" , type = "fixed", position = [0, -4.086, 0])
    pyrosim.Send_RD(name="half1half", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.Send_Joint(name = "half1half_half0half" , parent= "half1half" , child = "half0half" , type = "fixed", position = [0, -4.086, 0])
    pyrosim.Send_RD(name="half0half", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.Send_Joint(name = "half0half_one0" , parent= "half0half" , child = "one0" , type = "fixed", position = [2.88, 2.043, -2.043])
    pyrosim.Send_RD(name="one0", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.Send_Joint(name = "one0_one1" , parent= "one0" , child = "one1" , type = "fixed", position = [0, 4.086, 0])
    pyrosim.Send_RD(name="one1", pos=[0, 0, 0], size = [1, 1, 1], rpy = [0, 0, 0.62])
    pyrosim.End()
       
Generate_Body()